version: '3.8'

services:
  redis:
    build: ./redis
    expose:
      - 6379

  backend:
    build: ./backend
    volumes:
      - ./backend/data.:/usr/src/app/data
    ports:
      - 8000:8000
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /usr/src/app
        - action: rebuild
          path: ./backend/pyproject.toml


  frontend:
    stdin_open: true
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 5173
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  reverse_proxy:
    build: ./nginx
    ports:
      - 81:80
    depends_on:
      - backend
      - frontend
